header:
  version: 12

target:
  - machine-image

distro: auto

local_conf_header:
  standard: |
    VARIANT = "debug"
    CONF_VERSION = "2"

    INHERIT += "qfile"
    BBMULTICONFIG:append = " sa8775-flex gen5"

    SRC_DIR_ROOT := "${@os.path.abspath(os.path.join(d.getVar('COREBASE'), '../..'))}"
    PATH_TO_REPO := "git://${SRC_DIR_ROOT}"
    PROTO = "file"

    MIRRORS += "git://github.com \
        git://git.codelinaro.org/clo/yocto-mirrors/github/ \
        git://.*/.*/ git://git.codelinaro.org/clo/yocto-mirrors/ \
        https://.*/.*/ https://codelinaro.jfrog.io/artifactory/codelinaro-le/ \
    "

    BB_SIGNATURE_HANDLER = "OEEquivHash"
    BB_HASHSERVE ?= "auto"

    BUILDCFG_VARS += "VARIANT MACHINE_FEATURES"
    BBFILE_PATTERN_IGNORE_EMPTY_qcom = "1"
    BBFILE_PATTERN_IGNORE_EMPTY_qcom-hwe = "1"

    cust_id = "1020"
